# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleYoutubeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'youtube-ios-player-helper'
pod 'Alamofire'

  # Pods for SimpleYoutubeApp

end
